// -*- compile-command: "cd ../../wit && ./run-wit-bindgen.sh"; -*-

// wit-translate runs `wit-bindgen moonbit` and then translates its output into
// the "beautiful" Spin SDK structure that this repository has always used.
//
// wit-bindgen's MoonBit backend emits:
//
//	moon.mod.json
//	gen/{ffi.mbt,moon.pkg.json}
//	gen/interface/<ns>/<pkg>/<iface>/{top.mbt,ffi.mbt,moon.pkg.json}   (world exports)
//	interface/<ns>/<pkg>/<iface>/{top.mbt,ffi.mbt,moon.pkg.json,README.md}
//	world/<world>/{import.mbt,ffi_import.mbt,moon.pkg.json}
//
// with private `mbt_ffi_*` primitives duplicated into every generated package,
// kebab-case directory names, and the deprecated JSON manifest files.
//
// This program turns that into:
//
//	ffi/top_wasm.mbt            (hoisted, deduplicated, `pub` FFI primitives)
//	gen/{moon.pkg,ffi.mbt}      (thin `cabi_realloc` wrapper + link options)
//	interface/<ns>/<pkg>/<iface>/{moon.pkg,top.mbt,ffi.mbt,README.md}
//
// Exactly like the original layout: one shared `@ffi` package, camelCase
// interface directories, `moon.pkg` rather than `moon.pkg.json`, no `world/`
// directory, and no generated export trampoline (the application supplies
// `cabi_realloc` + `wasmExportHandle` itself).
//
// It must be run from the `wit/` directory (or via wit/run-wit-bindgen.sh),
// with `wit-bindgen` (>= 0.62.0) and `moon` in $PATH.
package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"unicode"
)

const (
	// moduleName is the MoonBit module name of this SDK; it is what
	// wit-bindgen uses to build the import paths in the generated code.
	moduleName = "gmlewis/spin-moonbit-sdk"

	// ffiImport is the shared FFI helper package every generated package uses.
	ffiImport = moduleName + "/ffi"

	// genDir is the wit-bindgen "program entrance" directory.
	genDir = "gen"
)

var (
	itemSepRE = regexp.MustCompile(`(?m)^///\|\s*$`)

	// generatedHeaderRE matches wit-bindgen's "DO NOT EDIT" banner.
	generatedHeaderRE = regexp.MustCompile("(?m)^// Generated by `wit-bindgen` ([0-9][^ ]*)\\. DO NOT EDIT!")

	// mbtFFIDefRE matches a definition of one of wit-bindgen's private FFI shims.
	mbtFFIDefRE = regexp.MustCompile(`(?m)^(?:#\w+\([^)]*\)\n)?(?:pub\s+)?(?:extern "wasm"\s+)?fn (mbt_ffi_[A-Za-z0-9_]+)`)

	// mbtFFIRefRE matches any reference to one of them.
	mbtFFIRefRE = regexp.MustCompile(`mbt_ffi_[A-Za-z0-9_]+`)

	// quotedPathRE matches an import path inside a moon.pkg file.
	quotedPathRE = regexp.MustCompile(`"[^"\n]*/[^"\n]*"`)

	// importBlockStartRE matches the opening of an import block.
	importBlockStartRE = regexp.MustCompile(`(?m)^import \{\n`)
)

// ffiOrder is the order in which the hoisted FFI primitives are written to
// ffi/top_wasm.mbt. Anything not listed is appended alphabetically.
var ffiOrder = []string{
	"extend8",
	"extend16",
	"store8",
	"load8_u",
	"load8",
	"store16",
	"load16",
	"load16_u",
	"store32",
	"load32",
	"store64",
	"load64",
	"storef32",
	"loadf32",
	"storef64",
	"loadf64",
	"malloc",
	"free",
	"copy",
	"str2ptr",
	"ptr2str",
	"bytes2ptr",
	"ptr2bytes",
	"uint_array2ptr",
	"uint64_array2ptr",
	"int_array2ptr",
	"int64_array2ptr",
	"float_array2ptr",
	"double_array2ptr",
	"ptr2uint_array",
	"ptr2uint64_array",
	"ptr2int_array",
	"ptr2int64_array",
	"ptr2float_array",
	"ptr2double_array",
	"cabi_realloc",
}

type ffiDef struct {
	name     string // without the mbt_ffi_ prefix
	full     string // with the mbt_ffi_ prefix
	body     string // full item text, no leading "///|"
	fromFile string
}

type renamer struct {
	// old base name -> new (camelCase) base name
	dirs map[string]string
}

func main() {
	log.SetFlags(0)

	var (
		witPath  = flag.String("wit", ".", "path to the WIT directory handed to wit-bindgen")
		repoRoot = flag.String("repo", "..", "path to the SDK repository root")
		wb       = flag.String("wit-bindgen", envOr("WIT_BINDGEN", "wit-bindgen"), "wit-bindgen executable")
		derive   = flag.String("derive", "debug,eq", "comma-separated `--derive-*` options; use `show,eq` to reproduce the pre-0.62 output")
		keep     = flag.Bool("keep", false, "keep the temporary wit-bindgen output directory")
		dryRun   = flag.Bool("n", false, "translate but do not install into the repository")
	)
	flag.Parse()

	absWit, err := filepath.Abs(*witPath)
	must(err)
	absRepo, err := filepath.Abs(*repoRoot)
	must(err)

	if !fileExists(filepath.Join(absRepo, "ffi", "moon.pkg")) {
		log.Fatalf("%v does not look like the Spin SDK repository root", absRepo)
	}

	tmp, err := os.MkdirTemp("", "wit-translate-")
	must(err)
	if !*keep && !*dryRun {
		defer os.RemoveAll(tmp)
	}
	log.Printf("Translating %v into %v (working dir %v)", absWit, absRepo, tmp)

	// 1. Generate the raw wit-bindgen output.
	args := []string{"moonbit", "--out-dir", tmp}
	for _, d := range strings.Split(*derive, ",") {
		if d = strings.TrimSpace(d); d != "" {
			args = append(args, "--derive-"+d)
		}
	}
	args = append(args, absWit)
	run("", *wb, args...)

	// 2. Let `moon fmt` do two jobs at once: migrate the deprecated
	// moon.mod.json/moon.pkg.json manifests to moon.mod/moon.pkg, and format
	// the generated MoonBit source (wit-bindgen emits unformatted code).
	run(tmp, "moon", "fmt")
	os.RemoveAll(filepath.Join(tmp, "_build"))

	// 3. Drop the generated module manifest: this repository owns its own.
	for _, f := range []string{"moon.mod", "moon.mod.json"} {
		os.Remove(filepath.Join(tmp, f))
	}

	// 4. Drop the world package: everything in it is already reachable through
	// the interface packages (the original script did `rm -rf world` too, but
	// fail loudly if upstream ever starts putting real code there).
	pruneWorld(tmp)

	// 5. Drop the generated export package -- the application supplies
	// `wasmExportHandle` itself (see examples/hello-world/external-exports.mbt).
	dropExportPackage(tmp)

	// 6. Rename kebab-case directories to this SDK's camelCase convention.
	ren := newRenamer()
	ren.renameDirs(tmp)
	ren.rewriteSources(tmp)

	// 7. Hoist the duplicated private FFI shims into one shared `ffi` package.
	ffiVersion, defs := hoistFFI(tmp)
	if ffiVersion == "" {
		log.Fatalf("could not determine the wit-bindgen version from the generated output")
	}
	writeFFIPackage(tmp, ffiVersion, defs)

	// 8. Write the `gen` package.
	writeGenPackage(tmp, ffiVersion)

	// 9. Drop the `warnings = "-44"` suppression wit-bindgen puts in every
	// package: after hoisting it is only needed where inline wasm remains,
	// i.e. the hand-written ffi package.
	dropUnneededWarnings(tmp)

	// 10. Give every package that now calls `@ffi.*` an import for it.
	addFFIImports(tmp)

	if *dryRun {
		log.Printf("Dry run: translated output left in %v", tmp)
		return
	}

	// 11. Install the translated tree into the repository.
	install(tmp, absRepo)

	// 12. Regenerate ffi/top_notwasm.mbt from ffi/top_wasm.mbt.
	run(absRepo, "go", "run", "cmd/gen-ffi-top-notwasm/main.go")

	// 13. Final formatting + interface files.
	run(absRepo, "moon", "fmt")
	run(absRepo, "moon", "info")
	log.Printf("Done.")
}

func envOr(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}

func run(dir string, name string, args ...string) {
	cmd := exec.Command(name, args...)
	if dir != "" {
		cmd.Dir = dir
	}
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		log.Fatalf("%v %v: %v", name, strings.Join(args, " "), err)
	}
}

// ---------------------------------------------------------------------------
// steps 4 & 5: prune generated packages this SDK does not want
// ---------------------------------------------------------------------------

func pruneWorld(tmp string) {
	worldDir := filepath.Join(tmp, "world")
	if !fileExists(worldDir) {
		return
	}
	var bad []string
	must(filepath.Walk(worldDir, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() || !strings.HasSuffix(path, ".mbt") {
			return err
		}
		_, items := splitItems(readFile(path))
		for _, item := range items {
			var code []string
			for _, line := range strings.Split(item, "\n") {
				if line = strings.TrimSpace(line); line != "" && !strings.HasPrefix(line, "///") {
					code = append(code, line)
				}
			}
			if len(code) > 0 {
				bad = append(bad, path)
			}
		}
		return nil
	}))
	if len(bad) > 0 {
		log.Fatalf("wit-bindgen now generates real code in world/: %v -- wit-translate must handle it", bad)
	}
	os.RemoveAll(worldDir)
}

// dropExportPackage removes the generated world-export trampolines and the
// import of them from gen/moon.pkg.
func dropExportPackage(tmp string) {
	exportDir := filepath.Join(tmp, genDir, "interface")
	if !fileExists(exportDir) {
		return
	}
	os.RemoveAll(exportDir)

	pkgPath := filepath.Join(tmp, genDir, "moon.pkg")
	src := readFile(pkgPath)
	src = removeImport(src, moduleName+"/"+genDir+"/")
	writeFile(pkgPath, src)
}

// removeImport drops every import entry whose path has the given prefix.
func removeImport(src, pathPrefix string) string {
	blk, ok := findImportBlock(src)
	if !ok {
		return src
	}
	var entries []string
	for _, line := range blk.entries {
		if p, _ := splitImportEntry(line); strings.HasPrefix(p, pathPrefix) {
			continue
		}
		entries = append(entries, line)
	}
	if len(entries) == 0 {
		return tidyPkg(joinBlocks(src[:blk.start], src[blk.end:]))
	}
	return tidyPkg(src[:blk.start] + renderImportBlock(entries) + src[blk.end:])
}

// ---------------------------------------------------------------------------
// step 6: kebab-case -> camelCase
// ---------------------------------------------------------------------------

func newRenamer() *renamer {
	return &renamer{dirs: map[string]string{}}
}

func (r *renamer) renameDirs(root string) {
	var dirs []string
	must(filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() && path != root && strings.Contains(filepath.Base(path), "-") {
			dirs = append(dirs, path)
		}
		return nil
	}))
	// Deepest first so that renaming a parent never invalidates a child path.
	sort.Slice(dirs, func(i, j int) bool { return len(dirs[i]) > len(dirs[j]) })
	for _, dir := range dirs {
		base := filepath.Base(dir)
		newBase := kebabToCamel(base)
		if newBase == base {
			continue
		}
		newPath := filepath.Join(filepath.Dir(dir), newBase)
		if fileExists(newPath) {
			log.Fatalf("cannot rename %v to %v: destination exists", dir, newPath)
		}
		must(os.Rename(dir, newPath))
		r.dirs[base] = newBase
	}
	if len(r.dirs) > 0 {
		var pairs []string
		for k, v := range r.dirs {
			pairs = append(pairs, k+" -> "+v)
		}
		sort.Strings(pairs)
		log.Printf("Renamed %v directories: %v", len(pairs), strings.Join(pairs, ", "))
	}
}

func (r *renamer) rewriteSources(root string) {
	must(filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() {
			return err
		}
		switch {
		case strings.HasSuffix(path, ".mbt"):
			src := readFile(path)
			out := src
			for old, newBase := range r.dirs {
				out = strings.ReplaceAll(out, "@"+old+".", "@"+newBase+".")
			}
			if out != src {
				writeFile(path, out)
			}
		case filepath.Base(path) == "moon.pkg":
			src := readFile(path)
			out := quotedPathRE.ReplaceAllStringFunc(src, func(q string) string {
				parts := strings.Split(strings.Trim(q, `"`), "/")
				for i, p := range parts {
					if newBase, ok := r.dirs[p]; ok {
						parts[i] = newBase
					}
				}
				return `"` + strings.Join(parts, "/") + `"`
			})
			if out != src {
				writeFile(path, out)
			}
		}
		return nil
	}))
}

// kebabToCamel converts "wall-clock" to "wallClock".
func kebabToCamel(s string) string {
	if !strings.Contains(s, "-") {
		return s
	}
	parts := strings.Split(s, "-")
	var b strings.Builder
	b.WriteString(parts[0])
	for _, p := range parts[1:] {
		if p == "" {
			continue
		}
		rs := []rune(p)
		rs[0] = unicode.ToUpper(rs[0])
		b.WriteString(string(rs))
	}
	return b.String()
}

// ---------------------------------------------------------------------------
// step 7: hoist the private FFI shims
// ---------------------------------------------------------------------------

// hoistFFI removes every `mbt_ffi_*` definition from the generated tree,
// rewrites all remaining references to `@ffi.<name>`, and returns the union of
// the definitions along with the wit-bindgen version that produced them.
func hoistFFI(root string) (string, []ffiDef) {
	defs := map[string]ffiDef{}
	version := ""

	files := mbtFiles(root)

	// Pass 1: collect and remove every definition.
	for _, path := range files {
		src := readFile(path)
		if version == "" {
			if m := generatedHeaderRE.FindStringSubmatch(src); m != nil {
				version = m[1]
			}
		}
		header, items := splitItems(src)
		var kept []string
		for _, item := range items {
			m := mbtFFIDefRE.FindStringSubmatch(item)
			if m == nil {
				kept = append(kept, item)
				continue
			}
			full := m[1]
			name := strings.TrimPrefix(full, "mbt_ffi_")
			body := strings.TrimRight(item, "\n")
			if prev, ok := defs[name]; ok {
				if normalizeWS(prev.body) != normalizeWS(body) {
					log.Fatalf("conflicting definitions of %v:\n%v\nvs (%v):\n%v", full, prev.body, prev.fromFile, body)
				}
				continue
			}
			defs[name] = ffiDef{name: name, full: full, body: body, fromFile: path}
		}
		if out := rebuild(header, kept); out != src {
			writeFile(path, out)
		}
	}

	// Pass 2: now that every definition is known, rewrite the references.
	for _, path := range files {
		if !fileExists(path) {
			continue
		}
		src := readFile(path)
		out := mbtFFIRefRE.ReplaceAllStringFunc(src, func(ref string) string {
			name := strings.TrimPrefix(ref, "mbt_ffi_")
			if _, ok := defs[name]; !ok {
				log.Fatalf("%v references unknown FFI shim %v", path, ref)
			}
			return "@ffi." + name
		})
		if out != src {
			writeFile(path, out)
		}
	}

	list := make([]ffiDef, 0, len(defs))
	for _, d := range defs {
		list = append(list, d)
	}
	rank := map[string]int{}
	for i, n := range ffiOrder {
		rank[n] = i
	}
	unknown := map[string]bool{}
	sort.Slice(list, func(i, j int) bool { return rankOf(rank, list[i].name, unknown) < rankOf(rank, list[j].name, unknown) })
	var names []string
	for _, d := range list {
		names = append(names, d.name)
	}
	if len(unknown) > 0 {
		var ks []string
		for k := range unknown {
			ks = append(ks, k)
		}
		sort.Strings(ks)
		log.Printf("NOTE: new FFI primitives not in ffiOrder (please add them): %v", ks)
	}
	log.Printf("Hoisted %v FFI primitives from wit-bindgen %v: %v", len(list), version, strings.Join(names, " "))
	return version, list
}

func rankOf(rank map[string]int, name string, unknown map[string]bool) int {
	if r, ok := rank[name]; ok {
		return r
	}
	unknown[name] = true
	return len(ffiOrder)
}

func mbtFiles(root string) []string {
	var files []string
	must(filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if !info.IsDir() && strings.HasSuffix(path, ".mbt") {
			files = append(files, path)
		}
		return nil
	}))
	sort.Strings(files)
	return files
}

// writeFFIPackage creates the shared ffi package from the hoisted definitions.
func writeFFIPackage(tmp, version string, defs []ffiDef) {
	var b strings.Builder
	fmt.Fprintf(&b, "// Generated by `wit-bindgen` %v. DO NOT EDIT!\n", version)
	for _, d := range defs {
		body := d.body
		// Rename the definition itself and make it public.
		switch {
		case strings.Contains(body, "pub fn "+d.full):
			body = strings.Replace(body, "pub fn "+d.full, "pub fn "+d.name, 1)
		case strings.Contains(body, "extern \"wasm\" fn "+d.full):
			body = strings.Replace(body, "extern \"wasm\" fn "+d.full, "pub extern \"wasm\" fn "+d.name, 1)
		case strings.Contains(body, "fn "+d.full):
			body = strings.Replace(body, "fn "+d.full, "pub fn "+d.name, 1)
		default:
			log.Fatalf("cannot find the declaration of %v in:\n%v", d.full, body)
		}
		// Rewrite the calls the bodies make to one another.
		body = mbtFFIRefRE.ReplaceAllStringFunc(body, func(ref string) string {
			return strings.TrimPrefix(ref, "mbt_ffi_")
		})
		b.WriteString("\n///|\n")
		b.WriteString(body)
		b.WriteString("\n")
	}

	dir := filepath.Join(tmp, "ffi")
	must(os.MkdirAll(dir, 0o755))
	writeFile(filepath.Join(dir, "top_wasm.mbt"), b.String())
}

// ---------------------------------------------------------------------------
// step 8: the `gen` package
// ---------------------------------------------------------------------------

// genFFI is the thin program-entrance wrapper the application imports.
const genFFI = "// Generated by `wit-bindgen` %[1]v. DO NOT EDIT!\n" + `
///|
pub fn cabi_realloc(
  src_offset : Int,
  src_size : Int,
  _dst_alignment : Int,
  dst_size : Int,
) -> Int {
  @ffi.cabi_realloc(src_offset, src_size, _dst_alignment, dst_size)
}
`

// writeGenPackage replaces gen/ffi.mbt with the thin wrapper and fixes up the
// link configuration that wit-bindgen emitted.
func writeGenPackage(tmp, version string) {
	dir := filepath.Join(tmp, genDir)
	if !fileExists(dir) {
		log.Fatalf("%v was not generated", dir)
	}
	writeFile(filepath.Join(dir, "ffi.mbt"), fmt.Sprintf(genFFI, version))

	pkgPath := filepath.Join(dir, "moon.pkg")
	src := readFile(pkgPath)
	// `cabi_realloc` now lives in gen/ffi.mbt under its own name.
	src = strings.ReplaceAll(src, `"mbt_ffi_cabi_realloc:cabi_realloc"`, `"cabi_realloc:cabi_realloc"`)
	writeFile(pkgPath, src)
}

// ---------------------------------------------------------------------------
// step 9: drop the now-unnecessary warning suppression
// ---------------------------------------------------------------------------

// dropUnneededWarnings removes the `warnings = "-44"` (invalid inline wasm)
// suppression from every generated package that no longer contains inline wasm.
func dropUnneededWarnings(root string) {
	dropped := 0
	must(filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() || filepath.Base(path) != "moon.pkg" {
			return err
		}
		dir := filepath.Dir(path)
		entries, err := os.ReadDir(dir)
		must(err)
		for _, e := range entries {
			if !e.IsDir() && strings.HasSuffix(e.Name(), ".mbt") &&
				strings.Contains(readFile(filepath.Join(dir, e.Name())), "#|") {
				return nil
			}
		}
		src := readFile(path)
		var kept []string
		changed := false
		for _, line := range strings.Split(src, "\n") {
			if strings.HasPrefix(strings.TrimSpace(line), "warnings") {
				changed = true
				continue
			}
			kept = append(kept, line)
		}
		if changed {
			writeFile(path, tidyPkg(strings.Join(kept, "\n")))
			dropped++
		}
		return nil
	}))
	log.Printf("Dropped the now-unnecessary warning suppression from %v packages", dropped)
}

// ---------------------------------------------------------------------------
// step 10: add the @ffi import where it is needed
// ---------------------------------------------------------------------------

func addFFIImports(root string) {
	var dirs []string
	must(filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil || !info.IsDir() {
			return err
		}
		if fileExists(filepath.Join(path, "moon.pkg")) {
			dirs = append(dirs, path)
		}
		return nil
	}))
	sort.Strings(dirs)
	count := 0
	for _, dir := range dirs {
		entries, err := os.ReadDir(dir)
		must(err)
		need := false
		for _, e := range entries {
			if e.IsDir() || !strings.HasSuffix(e.Name(), ".mbt") {
				continue
			}
			if strings.Contains(readFile(filepath.Join(dir, e.Name())), "@ffi.") {
				need = true
				break
			}
		}
		if !need {
			continue
		}
		addImport(filepath.Join(dir, "moon.pkg"), ffiImport, "ffi")
		count++
	}
	log.Printf("Added the @ffi import to %v packages", count)
}

// addImport inserts `"path" @alias,` into the import block of a moon.pkg file,
// creating the block if necessary, and keeps the list sorted.
func addImport(pkgPath, path, alias string) {
	src := readFile(pkgPath)
	entry := fmt.Sprintf("%q @%v", path, alias)

	blk, ok := findImportBlock(src)
	if ok {
		for _, line := range blk.entries {
			if p, _ := splitImportEntry(line); p == path {
				return // already there
			}
		}
		entries := append(append([]string(nil), blk.entries...), entry)
		src = src[:blk.start] + renderImportBlock(entries) + src[blk.end:]
	} else {
		src = joinBlocks(renderImportBlock([]string{entry}), src)
	}
	writeFile(pkgPath, tidyPkg(src))
}

// joinBlocks joins non-empty sections with a single blank line between them.
func joinBlocks(parts ...string) string {
	var blocks []string
	for _, p := range parts {
		if p = strings.Trim(p, "\n"); strings.TrimSpace(p) != "" {
			blocks = append(blocks, p)
		}
	}
	return strings.Join(blocks, "\n\n")
}

// importBlock describes the `import { ... }` block of a moon.pkg file.
type importBlock struct {
	start   int // index of the leading "import {"
	end     int // index just past the closing "}"
	entries []string
}

// findImportBlock locates the import block of a moon.pkg file, if any.
func findImportBlock(src string) (importBlock, bool) {
	loc := importBlockStartRE.FindStringIndex(src)
	if loc == nil {
		return importBlock{}, false
	}
	bodyStart := loc[1]
	rest := src[bodyStart:]
	if strings.HasPrefix(rest, "}") {
		return importBlock{start: loc[0], end: bodyStart + 1}, true
	}
	idx := strings.Index(rest, "\n}")
	if idx < 0 {
		return importBlock{}, false
	}
	return importBlock{
		start:   loc[0],
		end:     bodyStart + idx + len("\n}"),
		entries: parseImportEntries(rest[:idx]),
	}, true
}

// parseImportEntries returns the trimmed entries of an import block body.
func parseImportEntries(body string) []string {
	var entries []string
	for _, line := range strings.Split(body, "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		entries = append(entries, strings.TrimSuffix(line, ","))
	}
	return entries
}

// splitImportEntry splits `"path" @alias` into its path and alias.
func splitImportEntry(entry string) (string, string) {
	path := entry
	alias := ""
	if i := strings.Index(entry, `"`); i == 0 {
		if j := strings.Index(entry[1:], `"`); j >= 0 {
			path = entry[1 : 1+j]
			rest := strings.TrimSpace(entry[2+j:])
			alias = strings.TrimPrefix(rest, "@")
		}
	}
	return path, alias
}

// renderImportBlock writes a sorted import block (without a trailing newline).
func renderImportBlock(entries []string) string {
	sorted := append([]string(nil), entries...)
	sort.Slice(sorted, func(i, j int) bool {
		pi, ai := splitImportEntry(sorted[i])
		pj, aj := splitImportEntry(sorted[j])
		if pi != pj {
			return pi < pj
		}
		return ai < aj
	})
	var b strings.Builder
	b.WriteString("import {\n")
	for _, e := range sorted {
		b.WriteString("  " + e + ",\n")
	}
	b.WriteString("}")
	return b.String()
}

// ---------------------------------------------------------------------------
// step 10: install into the repository
// ---------------------------------------------------------------------------

func install(tmp, repo string) {
	for _, name := range []string{"interface", genDir} {
		dst := filepath.Join(repo, name)
		os.RemoveAll(dst)
		must(copyTree(filepath.Join(tmp, name), dst))
	}
	must(copyTree(filepath.Join(tmp, "ffi", "top_wasm.mbt"), filepath.Join(repo, "ffi", "top_wasm.mbt")))
}

func copyTree(src, dst string) error {
	info, err := os.Stat(src)
	if err != nil {
		return err
	}
	if !info.IsDir() {
		data, err := os.ReadFile(src)
		if err != nil {
			return err
		}
		return os.WriteFile(dst, data, 0o644)
	}
	if err := os.MkdirAll(dst, 0o755); err != nil {
		return err
	}
	entries, err := os.ReadDir(src)
	if err != nil {
		return err
	}
	for _, e := range entries {
		if err := copyTree(filepath.Join(src, e.Name()), filepath.Join(dst, e.Name())); err != nil {
			return err
		}
	}
	return nil
}

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

// splitItems splits a MoonBit file into its header (everything before the first
// "///|" separator) and its top-level items.
func splitItems(src string) (string, []string) {
	locs := itemSepRE.FindAllStringIndex(src, -1)
	if len(locs) == 0 {
		return src, nil
	}
	header := src[:locs[0][0]]
	var items []string
	for i, loc := range locs {
		start := loc[1]
		end := len(src)
		if i+1 < len(locs) {
			end = locs[i+1][0]
		}
		if item := strings.Trim(src[start:end], "\n"); item != "" {
			items = append(items, item)
		}
	}
	return header, items
}

func rebuild(header string, items []string) string {
	var b strings.Builder
	b.WriteString(strings.TrimRight(header, "\n"))
	b.WriteString("\n")
	for _, item := range items {
		b.WriteString("\n///|\n")
		b.WriteString(strings.TrimRight(item, "\n"))
		b.WriteString("\n")
	}
	return b.String()
}

var wsRE = regexp.MustCompile(`\s+`)

func normalizeWS(s string) string {
	return strings.TrimSpace(wsRE.ReplaceAllString(s, " "))
}

// tidyPkg normalises a moon.pkg file: blocks of non-blank lines separated by a
// single blank line, no leading or trailing blank lines, one trailing newline.
func tidyPkg(src string) string {
	var blocks []string
	var cur []string
	flush := func() {
		if len(cur) > 0 {
			blocks = append(blocks, strings.Join(cur, "\n"))
			cur = nil
		}
	}
	for _, line := range strings.Split(src, "\n") {
		if strings.TrimSpace(line) == "" {
			flush()
			continue
		}
		cur = append(cur, strings.TrimRight(line, " \t"))
	}
	flush()
	if len(blocks) == 0 {
		return ""
	}
	return strings.Join(blocks, "\n\n") + "\n"
}

func readFile(path string) string {
	data, err := os.ReadFile(path)
	must(err)
	return string(data)
}

func writeFile(path, content string) {
	must(os.WriteFile(path, []byte(content), 0o644))
}

func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

func must(err error) {
	if err != nil {
		log.Fatal(err)
	}
}
