package gmlewis:spin-moonbit-sdk@0.1.0;

/// The full world of a guest targeting an http-trigger
world http-trigger {
  include fermyon:spin/platform@2.0.0;
  export wasi:http/incoming-handler@0.2.0;
}
