manifest_version = "1"
id = "redis-mbt"
description = "Redis message handler using MoonBit"
tags = ["redis", "mbt"]

[parameters]
project-description = { type = "string",  prompt = "Description", default = "" }
redis-address = { type = "string", prompt = "Redis address", default = "redis://localhost:6379" }
http-path = { type = "string", prompt = "HTTP path", default = "/...", pattern = "^/\\S*$" }
