spin_manifest_version = 2

[application]
name = "{{project-name | kebab_case}}"
version = "0.1.0"
authors = ["{{authors}}"]
description = "{{project-description}}"

[[trigger.http]]
route = "{{http-path}}"
component = "{{project-name | kebab_case}}"

[component.{{project-name | kebab_case}}]
source = "{{project-name | kebab_case}}.wasm"
allowed_outbound_hosts = ["redis://*:*"]
[component.{{project-name | kebab_case}}.build]
command = """\
  moon build --target wasm && \
  wasm-tools component embed .mooncakes/gmlewis/spin-moonbit-sdk/wit ./target/wasm/release/build/{{project-name | kebab_case}}.wasm -o {{project-name | kebab_case}}.wasm --encoding utf16 -w http-trigger && \
  wasm-tools component new {{project-name | kebab_case}}.wasm -o {{project-name | kebab_case}}.wasm
  """
watch = ["**/*.mbt", "moon.mod.json", "moon.pkg.json"]
